УтвержденияТаблиц
oscript-library/asserts pull request #12
Opened 2024-12-06 10:06 UTC by Golovanoff

Доработал ситуации,  когда нужно сравнивать таблицы,  но структуры таблиц (разный состав/количество колонок) или количество строк в таблицах не равны.

Теперь падать не должно,  такие ситуации корректно обрабатываются.
Но теперь просится метод Содержит() для таблиц.

2024-12-07 07:05 UTC, nixel2007 commented
Сделай ребейз, пожалуйста.

И меня смущает, что текущий мастер бранч проходит тесты без ошибок. Значит, тестов на то, что ты пофиксил, не хватает. Можешь докинуть?

2024-12-07 10:48 UTC, Golovanoff commented
> Сделай ребейз, пожалуйста.
> 
> И меня смущает, что текущий мастер бранч проходит тесты без ошибок. Значит, тестов на то, что ты пофиксил, не хватает. Можешь докинуть? 

Функционал работал правильно, поэтому я тесты и не доработал. Просто при неравенстве таблиц отображение отличий могло не сформироваться корректно. 

Напилить тестов, что в определённых ситуациях исключения выбрасываются с нужным текстом? 

И зачем ребейз? Я текущий мастер смержил в ветку.

2024-12-11 06:43 UTC, artbear requested changes

2024-12-11 06:43 UTC, artbear commented on src/bdd-asserts-class.os
> +	Таб2 = ОжидаемоеЗначение.Скопировать();
предлагаю убрать лишнее копирование таблиц для улучшения производительности, т.к. нет изменения таблиц, кроме одного сценария проверки.

использовать Скопировать() только, когда отключен флаг УчитыватьПорядокСтрок 

т.е. 
```bsl
Таб1 = ПроверяемоеЗначение;
Таб2 = ОжидаемоеЗначение;

Если Не ПараметрыСравненияТаблиц.УчитыватьПорядокСтрок Тогда
	Таб1 = Таб1.Скопировать();
	Таб2 = Таб2.Скопировать();

	Таб1 = ОтсортироватьТаблицуПоВсемКолонкам(Таб1);
	Таб2 = ОтсортироватьТаблицуПоВсемКолонкам(Таб2);
КонецЕсли;
```

2024-12-16 14:10 UTC, Golovanoff commented on src/bdd-asserts-class.os
> +	Таб2 = ОжидаемоеЗначение.Скопировать();
сделал

2024-12-18 07:10 UTC, EvilBeaver commented
@artbear подтверди, пожалуйста, что все хорошо и можно вливать (или нельзя)

2024-12-28 10:16 UTC, artbear approved these changes

2024-12-28 10:16 UTC, merged

2024-12-28 10:16 UTC, artbear commented
> @artbear подтверди, пожалуйста, что все хорошо и можно вливать (или нельзя)

смержил ПР